#
# This is a strictly POSIX 1003.2 shell (Bourne shell) script 
# adding the LaTeX lm font package to the TeX Kernel system: 
# kerTeX.
#
# No shebang, since there is a bootstrapping problem: this script has
# to run on whatever host the kerTeX system runs on.
# It has to be invoked with whatever Bourne shell like interpreter is
# present on the host.
#
# C) 2012 Mark van Atten <Mark.vanAtten@univ-paris1.fr>
#    review for kerTeX 0.9999.4.0 by Thierry Laronde
# C) 2017, 2020, 2024
#   Thierry Laronde <tlaronde@polynum.com> : blunder
# in DVIPS block: shall not have leading blanks.
# All rights reserved and absolutely no warranty! Use at your own 
# risks.
#

# Needed post action (build, apply, remove) routines.
#
pkg_post_build()
{
	return 0 # bash errors on empty function...
}

pkg_post_apply()
{
	return 0 # bash errors on empty function...
}

pkg_post_remove()
{
	return 0 # bash errors on empty function...
}

#==================== AUTOMATIC PROCESSING
# First include the pecularities of the TeX kernel system host.
#
. which_kertex >&2

# Then we now how to find the library that defines routines and does
# some checks, argument processing and initializations. See the file
# directly for explanations.
#
. $KERTEX_BINDIR/lib/pkglib.sh

#==================== CUSTOM PROCESSING: we are in TMPDIR
#
#

#XXX should be fixed for kerTeX 1.0 release.
#
! pkg_is_installed latex/lm\
	|| pkg_error "Please remove lm@latex first!"
	

pkg_get

#===== CUSTOM PROCESSING FINISHED
#
# Time to do whether the build or the install.
#
pkg_do_action

# not reached
exit 0

# Since we have exited above, no need to comment out the CID.

BEGIN_CID
NAME: fonts/lm
VERSION: 2.005 (21 III 2021)
LICENCE: The GUST Font License (GFL)
KERTEX_VERSION: 0.99.22.0
KXPATH:
	fonts lm
	latex lm
DVIPS:
p +lm.map
SOURCES:
	LCD /lib/fonts/lm/tfm/
	GET /fonts/lm/fonts/tfm/public/lm/ec-lmr5.tfm
	GET cs-lmb10.tfm
	GET ec-lmr6.tfm
	GET cs-lmbo10.tfm
	GET ec-lmr7.tfm
	GET cs-lmbx10.tfm
	GET ec-lmr8.tfm
	GET cs-lmbx12.tfm
	GET ec-lmr9.tfm
	GET cs-lmbx5.tfm
	GET ec-lmri10.tfm
	GET cs-lmbx6.tfm
	GET ec-lmri12.tfm
	GET cs-lmbx7.tfm
	GET ec-lmri7.tfm
	GET cs-lmbx8.tfm
	GET ec-lmri8.tfm
	GET cs-lmbx9.tfm
	GET cs-lmtlco10.tfm
	GET cs-lmbxi10.tfm
	GET cs-lmtt10.tfm
	GET cs-lmbxo10.tfm
	GET cs-lmtlo10.tfm
	GET cs-lmcsc10.tfm
	GET cs-lmtt12.tfm
	GET cs-lmcsco10.tfm
	GET cs-lmtt8.tfm
	GET cs-lmdunh10.tfm
	GET cs-lmtt9.tfm
	GET cs-lmduno10.tfm
	GET ec-lmri9.tfm
	GET cs-lmr10.tfm
	GET ec-lmro10.tfm
	GET cs-lmr12.tfm
	GET ec-lmro12.tfm
	GET cs-lmr17.tfm
	GET ec-lmro17.tfm
	GET cs-lmr5.tfm
	GET ec-lmro8.tfm
	GET cs-lmr6.tfm
	GET ec-lmro9.tfm
	GET cs-lmr7.tfm
	GET ec-lmss10.tfm
	GET cs-lmr8.tfm
	GET ec-lmss12.tfm
	GET cs-lmr9.tfm
	GET ec-lmss17.tfm
	GET cs-lmri10.tfm
	GET ec-lmss8.tfm
	GET cs-lmri12.tfm
	GET ec-lmss9.tfm
	GET cs-lmri7.tfm
	GET ec-lmssbo10.tfm
	GET cs-lmri8.tfm
	GET ec-lmssbx10.tfm
	GET cs-lmri9.tfm
	GET ec-lmssdc10.tfm
	GET cs-lmro10.tfm
	GET ec-lmssdo10.tfm
	GET cs-lmro12.tfm
	GET ec-lmsso10.tfm
	GET cs-lmro17.tfm
	GET ec-lmsso12.tfm
	GET cs-lmro8.tfm
	GET ec-lmsso17.tfm
	GET cs-lmro9.tfm
	GET ec-lmsso8.tfm
	GET cs-lmss10.tfm
	GET ec-lmsso9.tfm
	GET cs-lmss12.tfm
	GET ec-lmssq8.tfm
	GET cs-lmss17.tfm
	GET ec-lmssqbo8.tfm
	GET cs-lmss8.tfm
	GET ec-lmssqbx8.tfm
	GET cs-lmss9.tfm
	GET ec-lmb10.tfm
	GET cs-lmssbo10.tfm
	GET cs-lmvtto10.tfm
	GET cs-lmssbx10.tfm
	GET ec-lmbo10.tfm
	GET cs-lmssdc10.tfm
	GET ec-lmbx10.tfm
	GET cs-lmssdo10.tfm
	GET ec-lmbx12.tfm
	GET cs-lmsso10.tfm
	GET ec-lmbx5.tfm
	GET cs-lmsso12.tfm
	GET ec-lmbx6.tfm
	GET cs-lmsso17.tfm
	GET ec-lmssqo8.tfm
	GET cs-lmsso8.tfm
	GET ec-lmtcsc10.tfm
	GET cs-lmsso9.tfm
	GET ec-lmtcso10.tfm
	GET cs-lmssq8.tfm
	GET ec-lmbx7.tfm
	GET cs-lmssqbo8.tfm
	GET ec-lmbx8.tfm
	GET cs-lmssqbx8.tfm
	GET ec-lmbx9.tfm
	GET cs-lmssqo8.tfm
	GET ec-lmbxi10.tfm
	GET cs-lmtcsc10.tfm
	GET ec-lmbxo10.tfm
	GET cs-lmtcso10.tfm
	GET ec-lmtk10.tfm
	GET cs-lmtk10.tfm
	GET ec-lmcsc10.tfm
	GET cs-lmtko10.tfm
	GET ec-lmtko10.tfm
	GET cs-lmtl10.tfm
	GET ec-lmcsco10.tfm
	GET cs-lmtlc10.tfm
	GET cs-lmtti10.tfm
	GET ec-lmdunh10.tfm
	GET cs-lmtto10.tfm
	GET ec-lmtl10.tfm
	GET cs-lmu10.tfm
	GET ec-lmduno10.tfm
	GET cs-lmvtk10.tfm
	GET ec-lmr10.tfm
	GET cs-lmvtko10.tfm
	GET cs-lmvtl10.tfm
	GET ec-lmr12.tfm
	GET cs-lmvtlo10.tfm
	GET ec-lmr17.tfm
	GET cs-lmvtt10.tfm
	GET ec-lmtlc10.tfm
	GET ec-lmtlco10.tfm
	GET ec-lmtlo10.tfm
	GET ec-lmtt10.tfm
	GET ec-lmtt12.tfm
	GET ec-lmtt8.tfm
	GET ec-lmtt9.tfm
	GET ec-lmtti10.tfm
	GET ec-lmtto10.tfm
	GET ec-lmu10.tfm
	GET ec-lmvtk10.tfm
	GET ec-lmvtko10.tfm
	GET ec-lmvtl10.tfm
	GET ec-lmvtlo10.tfm
	GET ec-lmvtt10.tfm
	GET ec-lmvtto10.tfm
	GET l7x-lmb10.tfm
	GET l7x-lmbo10.tfm
	GET l7x-lmbx10.tfm
	GET l7x-lmbx12.tfm
	GET l7x-lmbx5.tfm
	GET l7x-lmbx6.tfm
	GET l7x-lmbx7.tfm
	GET l7x-lmbx8.tfm
	GET l7x-lmbx9.tfm
	GET l7x-lmbxi10.tfm
	GET l7x-lmbxo10.tfm
	GET l7x-lmcsc10.tfm
	GET l7x-lmcsco10.tfm
	GET l7x-lmdunh10.tfm
	GET l7x-lmduno10.tfm
	GET l7x-lmr10.tfm
	GET l7x-lmr12.tfm
	GET l7x-lmr17.tfm
	GET l7x-lmr5.tfm
	GET l7x-lmr6.tfm
	GET l7x-lmr7.tfm
	GET l7x-lmr8.tfm
	GET l7x-lmr9.tfm
	GET l7x-lmri10.tfm
	GET l7x-lmri12.tfm
	GET l7x-lmri7.tfm
	GET l7x-lmri8.tfm
	GET l7x-lmri9.tfm
	GET l7x-lmro10.tfm
	GET l7x-lmro12.tfm
	GET l7x-lmro17.tfm
	GET l7x-lmro8.tfm
	GET l7x-lmro9.tfm
	GET l7x-lmss10.tfm
	GET l7x-lmss12.tfm
	GET l7x-lmss17.tfm
	GET l7x-lmss8.tfm
	GET l7x-lmss9.tfm
	GET l7x-lmssbo10.tfm
	GET l7x-lmssbx10.tfm
	GET l7x-lmssdc10.tfm
	GET l7x-lmssdo10.tfm
	GET l7x-lmsso10.tfm
	GET l7x-lmsso12.tfm
	GET l7x-lmsso17.tfm
	GET l7x-lmsso8.tfm
	GET l7x-lmsso9.tfm
	GET l7x-lmssq8.tfm
	GET l7x-lmssqbo8.tfm
	GET l7x-lmssqbx8.tfm
	GET l7x-lmssqo8.tfm
	GET l7x-lmtcsc10.tfm
	GET l7x-lmtcso10.tfm
	GET l7x-lmtk10.tfm
	GET l7x-lmtko10.tfm
	GET l7x-lmtl10.tfm
	GET l7x-lmtlc10.tfm
	GET l7x-lmtlco10.tfm
	GET l7x-lmtlo10.tfm
	GET l7x-lmtt10.tfm
	GET l7x-lmtt12.tfm
	GET l7x-lmtt8.tfm
	GET l7x-lmtt9.tfm
	GET l7x-lmtti10.tfm
	GET l7x-lmtto10.tfm
	GET l7x-lmu10.tfm
	GET l7x-lmvtk10.tfm
	GET l7x-lmvtko10.tfm
	GET l7x-lmvtl10.tfm
	GET l7x-lmvtlo10.tfm
	GET l7x-lmvtt10.tfm
	GET l7x-lmvtto10.tfm
	GET lmbsy10.tfm
	GET lmbsy5.tfm
	GET lmbsy7.tfm
	GET lmex10.tfm
	GET lmmi10.tfm
	GET lmmi12.tfm
	GET lmmi5.tfm
	GET lmmi6.tfm
	GET lmmi7.tfm
	GET lmmi8.tfm
	GET lmmi9.tfm
	GET lmmib10.tfm
	GET lmmib5.tfm
	GET lmmib7.tfm
	GET lmsy10.tfm
	GET lmsy5.tfm
	GET lmsy6.tfm
	GET lmsy7.tfm
	GET lmsy8.tfm
	GET lmsy9.tfm
	GET qx-lmb10.tfm
	GET qx-lmbo10.tfm
	GET qx-lmbx10.tfm
	GET qx-lmbx12.tfm
	GET qx-lmbx5.tfm
	GET qx-lmbx6.tfm
	GET qx-lmbx7.tfm
	GET qx-lmbx8.tfm
	GET qx-lmbx9.tfm
	GET qx-lmbxi10.tfm
	GET qx-lmbxo10.tfm
	GET qx-lmcsc10.tfm
	GET qx-lmcsco10.tfm
	GET qx-lmdunh10.tfm
	GET qx-lmduno10.tfm
	GET qx-lmr10.tfm
	GET qx-lmr12.tfm
	GET qx-lmr17.tfm
	GET qx-lmr5.tfm
	GET qx-lmr6.tfm
	GET qx-lmr7.tfm
	GET qx-lmr8.tfm
	GET qx-lmr9.tfm
	GET qx-lmri10.tfm
	GET qx-lmri12.tfm
	GET qx-lmri7.tfm
	GET qx-lmri8.tfm
	GET qx-lmri9.tfm
	GET qx-lmro10.tfm
	GET qx-lmro12.tfm
	GET qx-lmro17.tfm
	GET qx-lmro8.tfm
	GET qx-lmro9.tfm
	GET qx-lmss10.tfm
	GET qx-lmss12.tfm
	GET qx-lmss17.tfm
	GET qx-lmss8.tfm
	GET qx-lmss9.tfm
	GET qx-lmssbo10.tfm
	GET qx-lmsso8.tfm
	GET qx-lmssbx10.tfm
	GET qx-lmssdc10.tfm
	GET qx-lmssdo10.tfm
	GET qx-lmsso10.tfm
	GET qx-lmsso12.tfm
	GET qx-lmsso17.tfm
	GET qx-lmsso9.tfm
	GET qx-lmssq8.tfm
	GET qx-lmssqbo8.tfm
	GET qx-lmssqbx8.tfm
	GET qx-lmssqo8.tfm
	GET qx-lmtcsc10.tfm
	GET qx-lmtcso10.tfm
	GET qx-lmtk10.tfm
	GET qx-lmtko10.tfm
	GET qx-lmtl10.tfm
	GET qx-lmtlc10.tfm
	GET qx-lmtlco10.tfm
	GET qx-lmtlo10.tfm
	GET qx-lmtt10.tfm
	GET qx-lmtt12.tfm
	GET qx-lmtt8.tfm
	GET qx-lmtt9.tfm
	GET qx-lmtti10.tfm
	GET qx-lmtto10.tfm
	GET qx-lmu10.tfm
	GET qx-lmvtk10.tfm
	GET qx-lmvtko10.tfm
	GET qx-lmvtl10.tfm
	GET qx-lmvtlo10.tfm
	GET qx-lmvtt10.tfm
	GET qx-lmvtto10.tfm
	GET rm-lmb10.tfm
	GET rm-lmbo10.tfm
	GET rm-lmbx10.tfm
	GET rm-lmbx12.tfm
	GET rm-lmbx5.tfm
	GET rm-lmbx6.tfm
	GET rm-lmbx7.tfm
	GET rm-lmbx8.tfm
	GET rm-lmbx9.tfm
	GET rm-lmbxi10.tfm
	GET rm-lmbxo10.tfm
	GET rm-lmcsc10.tfm
	GET rm-lmcsco10.tfm
	GET rm-lmdunh10.tfm
	GET rm-lmduno10.tfm
	GET rm-lmr10.tfm
	GET rm-lmr12.tfm
	GET rm-lmr17.tfm
	GET rm-lmr5.tfm
	GET rm-lmr6.tfm
	GET rm-lmr7.tfm
	GET rm-lmr8.tfm
	GET rm-lmr9.tfm
	GET rm-lmri10.tfm
	GET rm-lmri12.tfm
	GET rm-lmri7.tfm
	GET rm-lmri8.tfm
	GET rm-lmri9.tfm
	GET rm-lmro10.tfm
	GET rm-lmro12.tfm
	GET rm-lmro17.tfm
	GET rm-lmro8.tfm
	GET rm-lmro9.tfm
	GET rm-lmss10.tfm
	GET rm-lmss12.tfm
	GET rm-lmss17.tfm
	GET rm-lmss8.tfm
	GET rm-lmss9.tfm
	GET rm-lmssbo10.tfm
	GET rm-lmssbx10.tfm
	GET rm-lmssdc10.tfm
	GET rm-lmssdo10.tfm
	GET rm-lmsso10.tfm
	GET rm-lmsso12.tfm
	GET rm-lmsso17.tfm
	GET rm-lmsso8.tfm
	GET rm-lmsso9.tfm
	GET rm-lmssq8.tfm
	GET rm-lmssqbo8.tfm
	GET rm-lmssqbx8.tfm
	GET rm-lmssqo8.tfm
	GET rm-lmtcsc10.tfm
	GET rm-lmtcso10.tfm
	GET rm-lmtk10.tfm
	GET rm-lmtko10.tfm
	GET rm-lmtl10.tfm
	GET rm-lmtlc10.tfm
	GET rm-lmtlco10.tfm
	GET rm-lmtlo10.tfm
	GET rm-lmtt10.tfm
	GET rm-lmtt12.tfm
	GET rm-lmtt8.tfm
	GET rm-lmtt9.tfm
	GET rm-lmtti10.tfm
	GET rm-lmtto10.tfm
	GET rm-lmu10.tfm
	GET rm-lmvtk10.tfm
	GET rm-lmvtko10.tfm
	GET rm-lmvtl10.tfm
	GET rm-lmvtlo10.tfm
	GET rm-lmvtt10.tfm
	GET rm-lmvtto10.tfm
	GET t5-lmb10.tfm
	GET t5-lmbo10.tfm
	GET t5-lmbx10.tfm
	GET t5-lmbx12.tfm
	GET t5-lmbx5.tfm
	GET t5-lmbx6.tfm
	GET t5-lmbx7.tfm
	GET t5-lmbx8.tfm
	GET t5-lmbx9.tfm
	GET t5-lmbxi10.tfm
	GET t5-lmbxo10.tfm
	GET t5-lmcsc10.tfm
	GET t5-lmcsco10.tfm
	GET t5-lmdunh10.tfm
	GET t5-lmduno10.tfm
	GET t5-lmr10.tfm
	GET t5-lmr12.tfm
	GET t5-lmr17.tfm
	GET t5-lmr5.tfm
	GET t5-lmr6.tfm
	GET t5-lmr7.tfm
	GET t5-lmr8.tfm
	GET t5-lmr9.tfm
	GET t5-lmri10.tfm
	GET t5-lmri12.tfm
	GET t5-lmri7.tfm
	GET t5-lmri8.tfm
	GET t5-lmri9.tfm
	GET t5-lmro10.tfm
	GET t5-lmro12.tfm
	GET t5-lmro17.tfm
	GET t5-lmro8.tfm
	GET t5-lmro9.tfm
	GET t5-lmss10.tfm
	GET t5-lmss12.tfm
	GET t5-lmss17.tfm
	GET t5-lmss8.tfm
	GET t5-lmss9.tfm
	GET t5-lmssbo10.tfm
	GET t5-lmssbx10.tfm
	GET t5-lmssdc10.tfm
	GET t5-lmssdo10.tfm
	GET t5-lmsso10.tfm
	GET t5-lmsso12.tfm
	GET t5-lmsso17.tfm
	GET t5-lmsso8.tfm
	GET t5-lmsso9.tfm
	GET t5-lmssq8.tfm
	GET t5-lmssqbo8.tfm
	GET t5-lmssqbx8.tfm
	GET t5-lmssqo8.tfm
	GET t5-lmtcsc10.tfm
	GET t5-lmtcso10.tfm
	GET t5-lmtk10.tfm
	GET t5-lmtko10.tfm
	GET t5-lmtl10.tfm
	GET t5-lmtlc10.tfm
	GET t5-lmtlco10.tfm
	GET t5-lmtlo10.tfm
	GET t5-lmtt10.tfm
	GET t5-lmtt12.tfm
	GET t5-lmtt8.tfm
	GET t5-lmtt9.tfm
	GET t5-lmtti10.tfm
	GET t5-lmtto10.tfm
	GET t5-lmu10.tfm
	GET t5-lmvtk10.tfm
	GET t5-lmvtko10.tfm
	GET t5-lmvtl10.tfm
	GET t5-lmvtlo10.tfm
	GET t5-lmvtt10.tfm
	GET t5-lmvtto10.tfm
	GET texnansi-lmb10.tfm
	GET texnansi-lmbo10.tfm
	GET texnansi-lmbx10.tfm
	GET texnansi-lmbx12.tfm
	GET texnansi-lmbx5.tfm
	GET texnansi-lmbx6.tfm
	GET texnansi-lmbx7.tfm
	GET texnansi-lmbx8.tfm
	GET texnansi-lmbx9.tfm
	GET texnansi-lmbxi10.tfm
	GET texnansi-lmbxo10.tfm
	GET texnansi-lmcsc10.tfm
	GET texnansi-lmcsco10.tfm
	GET texnansi-lmdunh10.tfm
	GET texnansi-lmduno10.tfm
	GET texnansi-lmr10.tfm
	GET texnansi-lmr12.tfm
	GET texnansi-lmr17.tfm
	GET texnansi-lmr5.tfm
	GET texnansi-lmr6.tfm
	GET texnansi-lmr7.tfm
	GET texnansi-lmr8.tfm
	GET texnansi-lmr9.tfm
	GET texnansi-lmri10.tfm
	GET texnansi-lmri12.tfm
	GET texnansi-lmri7.tfm
	GET texnansi-lmri8.tfm
	GET texnansi-lmri9.tfm
	GET texnansi-lmro10.tfm
	GET texnansi-lmro12.tfm
	GET texnansi-lmro17.tfm
	GET texnansi-lmro8.tfm
	GET texnansi-lmro9.tfm
	GET texnansi-lmss10.tfm
	GET texnansi-lmss12.tfm
	GET texnansi-lmss17.tfm
	GET texnansi-lmss8.tfm
	GET texnansi-lmss9.tfm
	GET texnansi-lmssbo10.tfm
	GET texnansi-lmssbx10.tfm
	GET texnansi-lmssdc10.tfm
	GET texnansi-lmssdo10.tfm
	GET texnansi-lmsso10.tfm
	GET texnansi-lmsso12.tfm
	GET texnansi-lmsso17.tfm
	GET texnansi-lmsso8.tfm
	GET texnansi-lmsso9.tfm
	GET texnansi-lmssq8.tfm
	GET texnansi-lmssqbo8.tfm
	GET texnansi-lmssqbx8.tfm
	GET texnansi-lmssqo8.tfm
	GET texnansi-lmtcsc10.tfm
	GET texnansi-lmtcso10.tfm
	GET texnansi-lmtk10.tfm
	GET texnansi-lmtko10.tfm
	GET texnansi-lmtl10.tfm
	GET texnansi-lmtlc10.tfm
	GET texnansi-lmtlco10.tfm
	GET texnansi-lmtlo10.tfm
	GET texnansi-lmtt10.tfm
	GET texnansi-lmtt12.tfm
	GET texnansi-lmtt8.tfm
	GET texnansi-lmtt9.tfm
	GET texnansi-lmtti10.tfm
	GET texnansi-lmtto10.tfm
	GET texnansi-lmu10.tfm
	GET texnansi-lmvtk10.tfm
	GET texnansi-lmvtko10.tfm
	GET texnansi-lmvtl10.tfm
	GET texnansi-lmvtlo10.tfm
	GET texnansi-lmvtt10.tfm
	GET texnansi-lmvtto10.tfm
	GET ts1-lmb10.tfm
	GET ts1-lmbo10.tfm
	GET ts1-lmbx10.tfm
	GET ts1-lmbx12.tfm
	GET ts1-lmbx5.tfm
	GET ts1-lmbx6.tfm
	GET ts1-lmbx7.tfm
	GET ts1-lmbx8.tfm
	GET ts1-lmbx9.tfm
	GET ts1-lmbxi10.tfm
	GET ts1-lmbxo10.tfm
	GET ts1-lmcsc10.tfm
	GET ts1-lmcsco10.tfm
	GET ts1-lmdunh10.tfm
	GET ts1-lmduno10.tfm
	GET ts1-lmr10.tfm
	GET ts1-lmr12.tfm
	GET ts1-lmr17.tfm
	GET ts1-lmr5.tfm
	GET ts1-lmr6.tfm
	GET ts1-lmr7.tfm
	GET ts1-lmr8.tfm
	GET ts1-lmr9.tfm
	GET ts1-lmri10.tfm
	GET ts1-lmri12.tfm
	GET ts1-lmri7.tfm
	GET ts1-lmri8.tfm
	GET ts1-lmri9.tfm
	GET ts1-lmro10.tfm
	GET ts1-lmro12.tfm
	GET ts1-lmro17.tfm
	GET ts1-lmro8.tfm
	GET ts1-lmro9.tfm
	GET ts1-lmss10.tfm
	GET ts1-lmss8.tfm
	GET ts1-lmss12.tfm
	GET ts1-lmss17.tfm
	GET ts1-lmss9.tfm
	GET ts1-lmssbo10.tfm
	GET ts1-lmssbx10.tfm
	GET ts1-lmssdc10.tfm
	GET ts1-lmssdo10.tfm
	GET ts1-lmsso10.tfm
	GET ts1-lmsso12.tfm
	GET ts1-lmsso17.tfm
	GET ts1-lmsso8.tfm
	GET ts1-lmsso9.tfm
	GET ts1-lmssq8.tfm
	GET ts1-lmssqbo8.tfm
	GET ts1-lmssqbx8.tfm
	GET ts1-lmssqo8.tfm
	GET ts1-lmtcsc10.tfm
	GET ts1-lmtcso10.tfm
	GET ts1-lmtk10.tfm
	GET ts1-lmtko10.tfm
	GET ts1-lmtl10.tfm
	GET ts1-lmtlc10.tfm
	GET ts1-lmtlco10.tfm
	GET ts1-lmtlo10.tfm
	GET ts1-lmtt10.tfm
	GET ts1-lmtt12.tfm
	GET ts1-lmtt8.tfm
	GET ts1-lmtt9.tfm
	GET ts1-lmtti10.tfm
	GET ts1-lmtto10.tfm
	GET ts1-lmu10.tfm
	GET ts1-lmvtk10.tfm
	GET ts1-lmvtko10.tfm
	GET ts1-lmvtl10.tfm
	GET ts1-lmvtlo10.tfm
	GET ts1-lmvtt10.tfm
	GET ts1-lmvtto10.tfm
	LCD ../pfb/
	GET /fonts/lm/fonts/type1/public/lm/lmr17.pfb
	GET lmb10.pfb
	GET lmbo10.pfb
	GET lmr5.pfb
	GET lmr6.pfb
	GET lmbsy10.pfb
	GET lmri7.pfb
	GET lmbsy5.pfb
	GET lmri8.pfb
	GET lmbsy7.pfb
	GET lmri9.pfb
	GET lmbx10.pfb
	GET lmro10.pfb
	GET lmbx12.pfb
	GET lmro12.pfb
	GET lmbx5.pfb
	GET lmro17.pfb
	GET lmbx6.pfb
	GET lmro8.pfb
	GET lmbx7.pfb
	GET lmro9.pfb
	GET lmbx8.pfb
	GET lmss10.pfb
	GET lmbx9.pfb
	GET lmss12.pfb
	GET lmbxi10.pfb
	GET lmss17.pfb
	GET lmbxo10.pfb
	GET lmss8.pfb
	GET lmcsc10.pfb
	GET lmss9.pfb
	GET lmcsco10.pfb
	GET lmssbo10.pfb
	GET lmdunh10.pfb
	GET lmssbx10.pfb
	GET lmduno10.pfb
	GET lmssdc10.pfb
	GET lmex10.pfb
	GET lmssdo10.pfb
	GET lmmi10.pfb
	GET lmsso10.pfb
	GET lmmi12.pfb
	GET lmsso12.pfb
	GET lmmi5.pfb
	GET lmsso17.pfb
	GET lmmi6.pfb
	GET lmsso8.pfb
	GET lmmi7.pfb
	GET lmsso9.pfb
	GET lmmi8.pfb
	GET lmssq8.pfb
	GET lmmi9.pfb
	GET lmssqbo8.pfb
	GET lmmib10.pfb
	GET lmssqbx8.pfb
	GET lmmib5.pfb
	GET lmssqo8.pfb
	GET lmmib7.pfb
	GET lmsy10.pfb
	GET lmr10.pfb
	GET lmsy5.pfb
	GET lmr12.pfb
	GET lmr7.pfb
	GET lmsy6.pfb
	GET lmr8.pfb
	GET lmsy7.pfb
	GET lmr9.pfb
	GET lmsy8.pfb
	GET lmri10.pfb
	GET lmsy9.pfb
	GET lmri12.pfb
	GET lmtcsc10.pfb
	GET lmtcso10.pfb
	GET lmtk10.pfb
	GET lmtko10.pfb
	GET lmtl10.pfb
	GET lmtlc10.pfb
	GET lmtlco10.pfb
	GET lmtlo10.pfb
	GET lmtt10.pfb
	GET lmtt12.pfb
	GET lmtt8.pfb
	GET lmtt9.pfb
	GET lmtti10.pfb
	GET lmtto10.pfb
	GET lmu10.pfb
	GET lmvtk10.pfb
	GET lmvtko10.pfb
	GET lmvtl10.pfb
	GET lmvtlo10.pfb
	GET lmvtt10.pfb
	GET lmvtto10.pfb
	LCD ../afm/
	GET /fonts/lm/fonts/afm/public/lm/lmss12.afm
	GET lmb10.afm
	GET lmss17.afm
	GET lmbo10.afm
	GET lmss9.afm
	GET lmbsy10.afm
	GET lmss8.afm
	GET lmssbo10.afm
	GET lmbsy5.afm
	GET lmssbx10.afm
	GET lmssqo8.afm
	GET lmbsy7.afm
	GET lmsy10.afm
	GET lmbx10.afm
	GET lmsy5.afm
	GET lmbx12.afm
	GET lmbx5.afm
	GET lmsy6.afm
	GET lmbx6.afm
	GET lmbx7.afm
	GET lmsy7.afm
	GET lmbx8.afm
	GET lmbx9.afm
	GET lmsy8.afm
	GET lmbxi10.afm
	GET lmbxo10.afm
	GET lmsy9.afm
	GET lmcsc10.afm
	GET lmcsco10.afm
	GET lmtcsc10.afm
	GET lmdunh10.afm
	GET lmtcso10.afm
	GET lmduno10.afm
	GET lmtk10.afm
	GET lmex10.afm
	GET lmtko10.afm
	GET lmtl10.afm
	GET lmmi10.afm
	GET lmtlc10.afm
	GET lmtlco10.afm
	GET lmmi12.afm
	GET lmtlo10.afm
	GET lmtt10.afm
	GET lmmi5.afm
	GET lmtt12.afm
	GET lmtt8.afm
	GET lmmi6.afm
	GET lmtt9.afm
	GET lmtti10.afm
	GET lmmi7.afm
	GET lmtto10.afm
	GET lmu10.afm
	GET lmmi8.afm
	GET lmvtk10.afm
	GET lmvtko10.afm
	GET lmmi9.afm
	GET lmvtl10.afm
	GET lmvtlo10.afm
	GET lmmib10.afm
	GET lmvtt10.afm
	GET lmvtto10.afm
	GET lmmib5.afm
	GET lmmib7.afm
	GET lmr10.afm
	GET lmr12.afm
	GET lmr17.afm
	GET lmr5.afm
	GET lmr6.afm
	GET lmr7.afm
	GET lmr8.afm
	GET lmr9.afm
	GET lmri10.afm
	GET lmri12.afm
	GET lmri7.afm
	GET lmri8.afm
	GET lmri9.afm
	GET lmro10.afm
	GET lmro12.afm
	GET lmro17.afm
	GET lmro8.afm
	GET lmro9.afm
	GET lmss10.afm
	GET lmssdc10.afm
	GET lmssdo10.afm
	GET lmsso10.afm
	GET lmsso12.afm
	GET lmsso17.afm
	GET lmsso8.afm
	GET lmsso9.afm
	GET lmssq8.afm
	GET lmssqbo8.afm
	GET lmssqbx8.afm
	LCD ../enc/
	GET /fonts/lm/fonts/enc/dvips/lm/lm-cs.enc
	GET lm-cssc.enc
	GET lm-cstt.enc
	GET lm-ec.enc
	GET lm-l7x.enc
	GET lm-mathex.enc
	GET lm-mathit.enc
	GET lm-mathsy.enc
	GET lm-qx.enc
	GET lm-qxsc.enc
	GET lm-qxtt.enc
	GET lm-rep-cmin.enc
	GET lm-rep-cmit.enc
	GET lm-rep-cmitt.enc
	GET lm-rep-cmrm.enc
	GET lm-rep-cmsc.enc
	GET lm-rep-cmtt.enc
	GET lm-rep-csin.enc
	GET lm-rep-csrm.enc
	GET lm-rep-cssc.enc
	GET lm-rep-cstt.enc
	GET lm-rep-plin.enc
	GET lm-rep-plit.enc
	GET lm-rep-plitt.enc
	GET lm-rep-plrm.enc
	GET lm-rep-plsc.enc
	GET lm-rep-pltt.enc
	GET lm-rep-t5psn.enc
	GET lm-rm.enc
	GET lm-rmsc.enc
	GET lm-rmtt.enc
	GET lm-t5.enc
	GET lm-texnansi.enc
	GET lm-ts1.enc
	LCD /lib/dvips/
	GET /fonts/lm/fonts/map/dvips/lm/lm-cs.map
	GET lm-ec.map
	GET lm-l7x.map
	GET lm-math.map
	GET lm-qx.map
	GET lm-rep-cmother.map
	GET lm-rep-cmtext-interpolated.map
	GET lm-rep-cmtext.map
	GET lm-rep-cstext.map
	GET lm-rep-pltext.map
	GET lm-rep-vntext.map
	GET lm-rm.map
	GET lm-t5.map
	GET lm-texnansi.map
	GET lm-ts1.map
	GET lm.map
	LCD /lib/latex/lm/
	GET /fonts/lm/tex/latex/lm/il2lmdh.fd
	GET il2lmr.fd
	GET il2lmss.fd
	GET il2lmssq.fd
	GET il2lmtt.fd
	GET il2lmvtt.fd
	GET l7xlmdh.fd
	GET l7xlmr.fd
	GET l7xlmss.fd
	GET l7xlmssq.fd
	GET l7xlmtt.fd
	GET l7xlmvtt.fd
	GET lmodern.sty
	GET ly1lmdh.fd
	GET ly1lmr.fd
	GET ly1lmss.fd
	GET ly1lmssq.fd
	GET ly1lmtt.fd
	GET ly1lmvtt.fd
	GET omllmm.fd
	GET omllmr.fd
	GET omslmr.fd
	GET omslmsy.fd
	GET omxlmex.fd
	GET ot1lmdh.fd
	GET ot1lmr.fd
	GET ot1lmss.fd
	GET ot1lmssq.fd
	GET ot1lmtt.fd
	GET ot1lmvtt.fd
	GET ot4lmdh.fd
	GET ot4lmr.fd
	GET ot4lmss.fd
	GET ot4lmssq.fd
	GET ot4lmtt.fd
	GET ot4lmvtt.fd
	GET qxlmdh.fd
	GET qxlmr.fd
	GET qxlmss.fd
	GET qxlmssq.fd
	GET qxlmtt.fd
	GET qxlmvtt.fd
	GET t1lmdh.fd
	GET t1lmr.fd
	GET t1lmss.fd
	GET t1lmssq.fd
	GET t1lmtt.fd
	GET t1lmvtt.fd
	GET t5lmdh.fd
	GET t5lmr.fd
	GET t5lmss.fd
	GET t5lmssq.fd
	GET t5lmtt.fd
	GET t5lmvtt.fd
	GET ts1lmdh.fd
	GET ts1lmr.fd
	GET ts1lmss.fd
	GET ts1lmssq.fd
	GET ts1lmtt.fd
	GET ts1lmvtt.fd
	GET /fonts/lm/doc/fonts/lm/GUST-FONT-LICENSE.TXT
	GET MANIFEST-Latin-Modern.TXT
	GET README-Latin-Modern.TXT
	GET lm-hist.txt
	GET lm-info.pdf
	GET tstlmot1.pdf
	GET tstlmot1.tex
	GET tstlmot4.pdf
	GET tstlmot4.tex
	GET tstlmqx.pdf
	GET tstlmqx.tex
	GET tstlmt1.pdf
	GET tstlmt1.tex
	GET tstlmts1.pdf
	GET tstlmts1.tex
END:
END_CID
